language: node_js
node_js:
- stable
before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
env:
  global:
    secure: jRnfeuVbyeUkZkPDRHUP68IfaRBPKhMcFhyKRwXw0d2CIgoBRUZVIF4fLs75KsmQqZant0QwZ3Upp3PRBk8vuXjZvksMs6RHrB3Cczbsn92ty2xMYKj2VFn5wW8Tu5Z9rXh3GdGmDyf5ugsE8UgsCWLZwrSfCIwxYZgWK0bJxnK4iMQsBbe/Ywp5pY50gPvAtqPJdg0dV6gIhrQpcUaBGgos8XDV+HYudZrO4Nr0IyEX08BQw2eJjbJ3X+DCOReU/1Xg1Usn7fmm4XS4IxkffTvuXJCe6EIeTcaul/asZm7JuABbm2/LDlo4kPDIXrR62Di21TXjtx0zcV4SIg2tntRJ/WkbY/dzRkUCBiRMi5uqVlL08axJ6UP11HwMEcxgqBtK96mRnIWyfrTPfDVOS3Rd2KKk3oAeStMlBbI6PuTtcDtAG8wxY4yp7p+bCLsFuLOC/npWxIwr5qAaJmO4pYTMuhWCWl3knjz4x1HEC5pTKupFB7l6GRbD0/hqtdTVajNSBaOZXYhBW44/d3/I0DYo/SknCHO74Bfa15SPLrO5xRmDL5Jqi5OUQgcNqmH0Oh6jZZ57r3pPuwpN8lsU8Aa75wXi+VwI80IYsZIMNLK4o/p21+oUnbC+/isc/DzEzhVjZEO0QizXjIKNyXBVvTHrs2ChRASnx0GNb+gSCP8=
